apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: playlist-example
  description: playlist-example
  annotations:
    github.com/project-slug: soapraj/playlist-example
    backstage.io/techdocs-ref: default:component:playlist-example
    sentry.io/project-slug: home-hub
spec:
  type: website
  lifecycle: experimentaltest
  owner: soapraj
